# Notebook 4 – Introduction to Pandas
### `04_Pandas_Basics.ipynb`

**Pandas** is a Python library used for **data analysis, manipulation, and cleaning**. It helps us work with structured data using **Series and DataFrames** and supports reading, writing, filtering, and analyzing data easily.

In [1]:
import pandas as pd
import numpy as np
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.5
NumPy version: 2.5.2

## 1. What is Pandas?

**Concept Explanation:**
Pandas (Python Data Analysis Library) is an open-source Python library built on top of **NumPy** that provides fast, flexible, and expressive data structures — mainly **Series** (1-D) and **DataFrame** (2-D) — designed to make working with structured (tabular) data easy and intuitive.

It is the backbone of the Python data science stack, sitting between raw data (CSV, SQL, Excel, JSON, APIs) and analysis/visualization/ML libraries (NumPy, Matplotlib, Scikit-learn).

**Real-World Example:**
A hospital records patient vitals (temperature, blood pressure, heart rate) every hour in a spreadsheet. Pandas can load this spreadsheet, clean missing readings, and compute daily averages per patient in a few lines of code.

**Business Example:**
An e-commerce company stores daily sales transactions. Analysts use Pandas to load millions of transaction rows, filter by region, and compute monthly revenue trends for the finance team's dashboard.

**AI/ML Example:**
Before training a machine learning model to predict customer churn, a data scientist uses Pandas to merge customer profile data with usage logs, handle missing values, and engineer new features (e.g., "average monthly usage") that feed into the model.

**Python Implementation:**

In [2]:
data = {
    "Employee": ["Asha", "Ravi", "Meera", "John"],
    "Department": ["Sales", "IT", "HR", "Sales"],
    "Salary": [55000, 72000, 60000, 58000]
}
df_preview = pd.DataFrame(data)
df_preview

  Employee Department  Salary
0     Asha      Sales   55000
1     Ravi         IT   72000
2    Meera         HR   60000
3     John      Sales   58000

**Output Explanation:**
The code creates a dictionary of lists and converts it into a Pandas **DataFrame** — a tabular structure similar to an Excel sheet or SQL table, with automatically generated row labels (index: 0, 1, 2, 3) and column headers (`Employee`, `Department`, `Salary`).

**Best Practices:**
- Always import pandas using the standard alias: `import pandas as pd`.
- Check the pandas version installed (`pd.__version__`) since syntax can differ across major versions (e.g., pandas 1.x vs 2.x).

**Common Mistakes:**
- Confusing Pandas with NumPy — Pandas is for **labeled, heterogeneous, tabular** data; NumPy is for **homogeneous numerical arrays**.
- Forgetting that Pandas is built on NumPy, so understanding basic NumPy concepts (arrays, dtypes) helps a lot.

## 2. Why Pandas?

**Concept Explanation:**
Pandas solves the problem of handling **real-world, messy, structured data** efficiently. Compared to plain Python lists/dictionaries or even NumPy arrays, Pandas offers:
- Labeled axes (row index + column names) instead of just positions
- Built-in handling of missing data (`NaN`)
- Powerful I/O tools (CSV, Excel, SQL, JSON, Parquet, etc.)
- Vectorized operations (fast, no explicit loops)
- Group-by, merge/join, pivot, and time-series functionality out of the box

**Real-World Example:**
A weather station logs temperature every minute for a year (~525,600 rows). Using plain Python loops to compute the monthly average would be slow and error-prone; Pandas does it in one line using `groupby`.

**Business Example:**
A retail chain wants to compare sales across 500 stores. Pandas' `groupby()` and `pivot_table()` let analysts summarize this instantly instead of writing manual aggregation logic.

**AI/ML Example:**
Feature engineering (creating new columns like `"purchase_frequency"` or `"days_since_last_login"`) is done almost entirely in Pandas before the data is handed off to a model in Scikit-learn or TensorFlow.

**Python Implementation:**

In [4]:
import time
n = 1_000_000
values = list(range(n))
start = time.time()
squared_loop = [v ** 2 for v in values]
loop_time = time.time() - start
s = pd.Series(values)
start = time.time()
squared_pandas = s ** 2
pandas_time = time.time() - start
print(f"Loop time:   {loop_time:.4f} seconds")
print(f"Pandas time: {pandas_time:.4f} seconds")

Loop time:   0.1446 seconds
Pandas time: 0.0043 seconds

**Output Explanation:**
The vectorized Pandas (NumPy-backed) operation is typically **significantly faster** than a native Python loop for large datasets because it executes in optimized, compiled C code under the hood rather than Python's interpreter loop.

**Best Practices:**
- Prefer vectorized Pandas/NumPy operations over `for` loops or `.apply()` with Python functions whenever possible.
- Use Pandas for exploratory data analysis (EDA) before moving to specialized big-data tools (Spark, Dask) if data grows beyond memory limits.

**Common Mistakes:**
- Using `.apply()` with a row-by-row Python function when a vectorized alternative exists — this negates Pandas' performance benefits.
- Assuming Pandas can handle unlimited data size — it is memory-bound (single machine, in-RAM).

## 3. Series

**Concept Explanation:**
A **Series** is a one-dimensional, labeled array capable of holding any data type (integers, strings, floats, Python objects). It is essentially a single column of a DataFrame, or a NumPy array with an attached **index**.

Structure: `values` + `index`

**Real-World Example:**
A single column of daily closing stock prices for one company, with dates as the index, is a perfect use case for a Series.

**Business Example:**
Tracking a single KPI over time — e.g., monthly revenue for one product line — is naturally represented as a Series (index = month, values = revenue).

**AI/ML Example:**
The target/label column (`y`) in a supervised learning problem — e.g., "will customer churn: Yes/No" — is often extracted from a DataFrame as a Series before being passed to a model.

**Python Implementation:**

In [5]:
temps = pd.Series([30.5, 32.1, 29.8, 31.0], name="Temperature")
print(temps)
print("\nType:", type(temps))

0    30.5
1    32.1
2    29.8
3    31.0
Name: Temperature, dtype: float64

Type: <class 'pandas.Series'>

In [6]:
monthly_revenue = pd.Series(
    [12000, 15000, 11000, 18000],
    index=["Jan", "Feb", "Mar", "Apr"],
    name="Revenue"
)
print(monthly_revenue)
print("\nRevenue in Feb:", monthly_revenue["Feb"])
print("Revenue > 12000:\n", monthly_revenue[monthly_revenue > 12000])

Jan    12000
Feb    15000
Mar    11000
Apr    18000
Name: Revenue, dtype: int64

Revenue in Feb: 15000
Revenue > 12000:
 Feb    15000
Apr    18000
Name: Revenue, dtype: int64

**Output Explanation:**
- The first Series uses a default integer index (0, 1, 2, 3).
- The second Series uses custom labels ("Jan", "Feb", ...) as its index, enabling label-based access (`monthly_revenue["Feb"]`) instead of only position-based access.
- Boolean filtering (`monthly_revenue > 12000`) returns a new Series containing only rows that satisfy the condition — a core Pandas pattern used everywhere.

**Best Practices:**
- Give your Series a meaningful `name` — it becomes the column name if later converted into a DataFrame.
- Use custom indexes (dates, IDs, categories) to make lookups more intuitive.

**Common Mistakes:**
- Mixing up Series indexing with plain Python list indexing — Pandas indexing can be label-based (`.loc`) or position-based (`.iloc`), and confusing the two causes subtle bugs.
- Forgetting that Series operations align by index — arithmetic between two Series matches on index labels, not position, which can produce `NaN` for mismatched labels.

## 4. DataFrame

**Concept Explanation:**
A **DataFrame** is a two-dimensional, labeled data structure with columns that can hold different data types (like an Excel sheet or SQL table). It is essentially a collection of Series objects sharing the same index.

Structure: rows (index) × columns, each column being a Series.

**Real-World Example:**
A student report card with columns like `Name`, `Subject`, `Marks`, and `Grade` is a natural DataFrame.

**Business Example:**
A company's HR system storing `EmployeeID`, `Name`, `Department`, `Salary`, and `JoinDate` for every employee is typically loaded into a DataFrame for payroll analysis.

**AI/ML Example:**
The full feature matrix used to train a model — with columns like `age`, `income`, `credit_score`, and a `default` label — is stored and manipulated as a DataFrame before being converted to NumPy arrays for model training.

**Python Implementation:**

In [7]:
data = {
    "EmployeeID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meera", "John"],
    "Department": ["Sales", "IT", "HR", "Sales"],
    "Salary": [55000, 72000, 60000, 58000],
    "JoinDate": pd.to_datetime(["2021-03-15", "2019-07-01", "2022-01-10", "2020-11-23"])
}
df = pd.DataFrame(data)
df

   EmployeeID   Name Department  Salary   JoinDate
0         101   Asha      Sales   55000 2021-03-15
1         102   Ravi         IT   72000 2019-07-01
2         103  Meera         HR   60000 2022-01-10
3         104   John      Sales   58000 2020-11-23

In [8]:
print("Shape:", df.shape)
print("\nColumn names:", list(df.columns))
print("\nData types:\n", df.dtypes)
print("\nSummary statistics:\n", df.describe())

Shape: (4, 5)

Column names: ['EmployeeID', 'Name', 'Department', 'Salary', 'JoinDate']

Data types:
 EmployeeID             int64
Name                     str
Department               str
Salary                 int64
JoinDate      datetime64[us]
dtype: object

Summary statistics:
        EmployeeID        Salary             JoinDate
count    4.000000      4.000000                    4
mean   102.500000  61250.000000  2020-11-26 12:00:00
min    101.000000  55000.000000  2019-07-01 00:00:00
25%    101.750000  57250.000000  2020-07-18 06:00:00
50%    102.500000  59000.000000  2021-01-18 00:00:00
75%    103.250000  63000.000000  2021-05-29 06:00:00
max    104.000000  72000.000000  2022-01-10 00:00:00
std      1.290994   7455.423082                  NaN

**Output Explanation:**
- `df.shape` returns `(rows, columns)`.
- `df.columns` lists all column labels.
- `df.dtypes` shows the data type stored in each column (important for memory usage and valid operations).
- `df.describe()` produces summary statistics (count, mean, std, min, quartiles, max) for numeric columns only, by default.

**Best Practices:**
- Always inspect a new DataFrame with `.head()`, `.info()`, `.shape`, and `.describe()` before analysis.
- Use meaningful, consistent column names (snake_case is common in Python projects).

**Common Mistakes:**
- Assuming all columns are numeric when calling `.describe()` — non-numeric columns are excluded unless `include='all'` is specified.
- Modifying a DataFrame slice without realizing it may be a "view" vs a "copy," triggering the infamous `SettingWithCopyWarning`.

## 5. Creating DataFrames

**Concept Explanation:**
DataFrames can be created from many sources: Python dictionaries, lists of lists, lists of dictionaries, NumPy arrays, Series, or external files (CSV, Excel, SQL, JSON). Knowing multiple creation methods is essential because real data arrives in different shapes.

**Real-World Example:**
A researcher manually enters a small dataset of experiment results as a list of dictionaries (one dict per observation) and converts it to a DataFrame for analysis.

**Business Example:**
A marketing analyst combines results from an API call (returned as JSON/list of dicts) into a single DataFrame for campaign performance analysis.

**AI/ML Example:**
A NumPy array of image pixel statistics (mean brightness, contrast, etc.) generated during preprocessing is converted into a DataFrame so it can be merged with labeled metadata for model training.

**Python Implementation:**

In [9]:
df1 = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df2 = pd.DataFrame([
    {"A": 1, "B": 4},
    {"A": 2, "B": 5},
    {"A": 3, "B": 6}
])
df3 = pd.DataFrame([[1, 4], [2, 5], [3, 6]], columns=["A", "B"])
df4 = pd.DataFrame(np.array([[1, 4], [2, 5], [3, 6]]), columns=["A", "B"])
print("df1:\n", df1, "\n")
print("df2:\n", df2, "\n")
print("df3:\n", df3, "\n")
print("df4:\n", df4)

df1:
    A  B
0  1  4
1  2  5
2  3  6

df2:
    A  B
0  1  4
1  2  5
2  3  6

df3:
    A  B
0  1  4
1  2  5
2  3  6

df4:
    A  B
0  1  4
1  2  5
2  3  6

**Output Explanation:**
All four approaches produce an identical DataFrame with columns `A` and `B` and 3 rows — demonstrating Pandas' flexibility in accepting different input formats.

**Best Practices:**
- Use a **dictionary of lists** when you already have column-oriented data.
- Use a **list of dictionaries** when data arrives row-by-row (e.g., from an API or loop).
- Always specify `columns=` explicitly when creating from raw lists/arrays to avoid ambiguous default integer column names.

**Common Mistakes:**
- Passing lists of unequal length in a dictionary → raises a `ValueError`.
- Forgetting that a list of lists without `columns=` results in unlabeled integer column names (0, 1, 2...), reducing readability.

## 6. Data Types

**Concept Explanation:**
Every column in a Pandas DataFrame has a **dtype** that determines what operations are valid and how much memory it consumes. Common dtypes include:
- `int64` / `float64` — numeric
- `object` — usually strings or mixed types
- `bool` — True/False
- `datetime64[ns]` — dates/timestamps
- `category` — memory-efficient encoding for repeated string values

**Real-World Example:**
A dataset of vehicle registrations may have `RegistrationDate` (datetime), `VehicleType` (category), and `Mileage` (float) — each needing correct dtypes for accurate analysis.

**Business Example:**
Storing a `CustomerSegment` column (e.g., "Gold", "Silver", "Bronze") as a `category` dtype instead of plain text drastically reduces memory usage in large customer databases.

**AI/ML Example:**
Before feeding data into a model, categorical text columns (like `country` or `product_category`) must be identified and encoded (one-hot/label encoding); this starts with checking `.dtypes` to distinguish numeric vs categorical features.

**Python Implementation:**

In [10]:
df_types = pd.DataFrame({
    "id": [1, 2, 3],
    "price": [19.99, 5.49, 100.0],
    "in_stock": [True, False, True],
    "category": ["Electronics", "Grocery", "Electronics"],
    "added_on": pd.to_datetime(["2024-01-01", "2024-02-15", "2024-03-10"])
})
print(df_types.dtypes)
df_types["category"] = df_types["category"].astype("category")
print("\nAfter conversion:\n", df_types.dtypes)
print("\nMemory usage (bytes):\n", df_types.memory_usage(deep=True))

id                   int64
price              float64
in_stock              bool
category               str
added_on    datetime64[us]
dtype: object

After conversion:
 id                   int64
price              float64
in_stock              bool
category          category
added_on    datetime64[us]
dtype: object

Memory usage (bytes):
 Index       132
id           24
price        24
in_stock      3
category    119
added_on     24
dtype: int64

**Output Explanation:**
The `dtypes` output shows each column's inferred type (`int64`, `float64`, `bool`, `object`, `datetime64[ns]`). After converting `category` to the `category` dtype, Pandas stores it internally as integer codes mapped to unique labels, which is visible as a change in `dtypes` and typically reduces `memory_usage`.

**Best Practices:**
- Explicitly convert columns to `datetime64` using `pd.to_datetime()` for any date/time data — never leave dates as strings.
- Use `category` dtype for columns with a limited set of repeated string values (e.g., country, gender, status) to save memory and speed up group operations.

**Common Mistakes:**
- Leaving numeric-looking data as `object` (string) dtype, which silently breaks arithmetic operations or sorting.
- Forgetting that `NaN` in an integer column forces Pandas to upcast the whole column to `float64` (since classic NumPy integers can't hold `NaN`).

## 7. Index

**Concept Explanation:**
The **Index** is the set of labels for the rows of a Series/DataFrame. It enables fast lookups, alignment during arithmetic operations, and merging/joining. By default, Pandas assigns a `RangeIndex` (0, 1, 2, ...), but any column (or combination of columns) can be set as a custom index.

**Real-World Example:**
In a time-series dataset of daily temperature readings, setting the `Date` column as the index makes it trivial to slice data by date range (e.g., `df["2024-01":"2024-03"]`).

**Business Example:**
Setting `CustomerID` as the index of a customer table allows O(1)-like fast lookups of a specific customer's data using `.loc[]`.

**AI/ML Example:**
When merging multiple feature tables (e.g., transaction features + demographic features) for the same `UserID`, setting `UserID` as the index in both DataFrames makes the join fast and unambiguous.

**Python Implementation:**

In [11]:
df_idx = pd.DataFrame({
    "CustomerID": [101, 102, 103],
    "Name": ["Asha", "Ravi", "Meera"],
    "TotalSpend": [2500, 4200, 1800]
})
df_idx_set = df_idx.set_index("CustomerID")
print(df_idx_set)
print("\nCustomer 102 details:\n", df_idx_set.loc[102])
df_reset = df_idx_set.reset_index()
print("\nAfter reset_index():\n", df_reset)

             Name  TotalSpend
CustomerID
101          Asha        2500
102          Ravi        4200
103         Meera        1800

Customer 102 details:
 Name          Ravi
TotalSpend    4200
Name: 102, dtype: object

After reset_index():
    CustomerID   Name  TotalSpend
0         101   Asha        2500
1         102   Ravi        4200
2         103  Meera        1800

**Output Explanation:**
`set_index("CustomerID")` moves that column out of the regular columns and makes it the row label, enabling `.loc[102]` to directly retrieve that customer's row. `reset_index()` reverses this, turning the index back into a regular column and restoring a default integer `RangeIndex`.

**Best Practices:**
- Use meaningful business keys (IDs, dates) as the index when you'll frequently look up or merge on that column.
- Use `df.reset_index(drop=True)` after filtering/sorting operations to keep index values clean and sequential, if the old index isn't needed.

**Common Mistakes:**
- Confusing `.loc[]` (label-based) with `.iloc[]` (position-based) indexing — a very common source of bugs, especially after filtering (where the index is no longer sequential).
- Setting a non-unique column as the index, which can cause unexpected duplicate rows during lookups/merges.

## 8. Columns

**Concept Explanation:**
Columns are the labeled fields (variables) of a DataFrame. Pandas provides many ways to select, rename, add, reorder, and drop columns — these are among the most frequently used operations in real-world data work.

**Real-World Example:**
A survey dataset might have poorly named columns like `Q1`, `Q2`, `Q3` that need renaming to `age_group`, `satisfaction_score`, `will_recommend` for clarity.

**Business Example:**
A sales DataFrame with columns `unit_price` and `quantity` often needs a new derived column `total_revenue = unit_price * quantity` for reporting.

**AI/ML Example:**
Dropping irrelevant columns (like `customer_name` or `transaction_id`, which have no predictive value and risk leaking identity) is a standard step before model training.

**Python Implementation:**

In [12]:
df_cols = pd.DataFrame({
    "unit_price": [100, 250, 75],
    "quantity": [3, 2, 5],
    "customer_name": ["Asha", "Ravi", "Meera"]
})
df_cols["total_revenue"] = df_cols["unit_price"] * df_cols["quantity"]
df_cols = df_cols.rename(columns={"unit_price": "price_per_unit"})
subset = df_cols[["price_per_unit", "total_revenue"]]
df_cols_dropped = df_cols.drop(columns=["customer_name"])
print("Full DataFrame:\n", df_cols)
print("\nSubset:\n", subset)
print("\nDropped 'customer_name':\n", df_cols_dropped)

Full DataFrame:
    price_per_unit  quantity customer_name  total_revenue
0             100         3          Asha            300
1             250         2          Ravi            500
2              75         5         Meera            375

Subset:
    price_per_unit  total_revenue
0             100            300
1             250            500
2              75            375

Dropped 'customer_name':
    price_per_unit  quantity  total_revenue
0             100         3            300
1             250         2            500
2              75         5            375

**Output Explanation:**
- Assigning `df_cols["total_revenue"] = ...` creates a new column computed element-wise from existing columns.
- `.rename(columns={...})` changes column labels without altering data.
- `df_cols[[...]]` (double brackets) selects a subset of columns and returns a DataFrame (single brackets on one column return a Series).
- `.drop(columns=[...])` removes a column non-destructively unless `inplace=True` is used.

**Best Practices:**
- Use double square brackets `df[["col1", "col2"]]` to select multiple columns as a DataFrame; single brackets `df["col1"]` return a Series.
- Prefer `df.drop(columns=[...])` over `del df["col"]` for clarity and chainability.

**Common Mistakes:**
- Using `inplace=True` carelessly — it can silently modify the original DataFrame and make code harder to debug; explicit reassignment (`df = df.drop(...)`) is often clearer.
- Typos in column names raise `KeyError` — always verify with `df.columns` first.

## 9. Reading Data

**Concept Explanation:**
Pandas provides `read_*` functions to import data from virtually any source: `read_csv()`, `read_excel()`, `read_json()`, `read_sql()`, `read_parquet()`, `read_html()`, and more. This is usually the **first step** in any real data workflow.

**Real-World Example:**
A meteorologist downloads a CSV of historical weather data and loads it with `pd.read_csv("weather.csv")` to begin analysis.

**Business Example:**
A finance team exports transaction data from their ERP system into an Excel file, which is then loaded into Pandas with `pd.read_excel()` for month-end reporting.

**AI/ML Example:**
A machine learning pipeline reads training data directly from a SQL database using `pd.read_sql()` to always work with the freshest available data.

**Python Implementation:**

In [13]:
sample_data = pd.DataFrame({
    "product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "price": [55000, 25000, 18000, 12000],
    "units_sold": [12, 45, 30, 20]
})
sample_data.to_csv("sample_sales.csv", index=False)  
df_read = pd.read_csv("sample_sales.csv")
print(df_read)
print("\nInfo:")
df_read.info()

   product  price  units_sold
0   Laptop  55000          12
1    Phone  25000          45
2   Tablet  18000          30
3  Monitor  12000          20

Info:
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     4 non-null      str
 1   price       4 non-null      int64
 2   units_sold  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

**Output Explanation:**
`pd.read_csv()` parses the CSV file into a DataFrame, automatically inferring column names (from the header row) and data types. `.info()` confirms the number of entries, column dtypes, and memory usage — a quick sanity check after loading any file.

**Best Practices:**
- Always inspect the file structure first (delimiter, header row, encoding) before reading, especially for messy real-world files.
- Use parameters like `usecols`, `dtype`, `parse_dates`, and `nrows` to control memory usage and correctness when reading large files.
- Wrap file reads in `try/except` in production code to handle missing files or malformed data gracefully.

**Common Mistakes:**
- Forgetting `index=False` when a file was written with an unwanted extra index column, leading to a stray `"Unnamed: 0"` column upon reading.
- Not specifying `encoding` for files with non-UTF-8 characters, causing `UnicodeDecodeError`.
- Reading huge files entirely into memory without using `chunksize` or column filters, causing memory errors.

## 10. Writing Data

**Concept Explanation:**
Just as Pandas can read from many formats, it can also **write** DataFrames back out using `to_csv()`, `to_excel()`, `to_json()`, `to_sql()`, `to_parquet()`, etc. This is essential for saving processed/cleaned data, generating reports, or feeding data into other systems.

**Real-World Example:**
After cleaning a messy survey dataset, a researcher saves the cleaned version using `df.to_csv("cleaned_survey.csv", index=False)` for sharing with colleagues.

**Business Example:**
A monthly sales report DataFrame is exported to Excel with `df.to_excel("monthly_report.xlsx")` and emailed to stakeholders.

**AI/ML Example:**
Engineered features are saved to a Parquet file (`df.to_parquet("features.parquet")`) for efficient, compressed storage before being loaded into a model training pipeline.

**Python Implementation:**

In [14]:
df_read["revenue"] = df_read["price"] * df_read["units_sold"]
df_read.to_csv("sales_with_revenue.csv", index=False)
df_read.to_json("sales_with_revenue.json", orient="records", indent=2)
print("Files written successfully.")
print("\nPreview of saved DataFrame:\n", df_read)
verify = pd.read_json("sales_with_revenue.json")
print("\nRe-loaded from JSON:\n", verify)

Files written successfully.

Preview of saved DataFrame:
    product  price  units_sold  revenue
0   Laptop  55000          12   660000
1    Phone  25000          45  1125000
2   Tablet  18000          30   540000
3  Monitor  12000          20   240000

Re-loaded from JSON:
    product  price  units_sold  revenue
0   Laptop  55000          12   660000
1    Phone  25000          45  1125000
2   Tablet  18000          30   540000
3  Monitor  12000          20   240000

**Output Explanation:**
`to_csv(index=False)` writes the DataFrame without the row index as an extra column — a very common best practice. `to_json(orient="records")` writes each row as a JSON object in a list, a format friendly for APIs and web applications. Reading the JSON back confirms the data was saved and can be restored correctly.

**Best Practices:**
- Use `index=False` in `to_csv()`/`to_excel()` unless the index carries meaningful information you want to preserve.
- Choose efficient formats like Parquet for large datasets that will be reloaded into Pandas/Spark later (faster + smaller than CSV).
- Version or timestamp output filenames in production pipelines to avoid overwriting important data.

**Common Mistakes:**
- Forgetting `index=False`, resulting in an unwanted extra "Unnamed: 0" column on re-read.
- Overwriting the original raw data file with processed data, losing the ability to reproduce results from scratch.
- Not checking disk space / file permissions before writing large files in production environments.

## Overall Advantages of Pandas

1. **Ease of use** – Intuitive, readable syntax close to natural language (`df[df["age"] > 30]`).
2. **Rich functionality** – Built-in support for missing data handling, merging/joining, grouping, pivoting, and time-series analysis.
3. **Performance** – Vectorized operations built on NumPy/C are much faster than pure Python loops.
4. **Wide I/O support** – Reads/writes CSV, Excel, SQL, JSON, Parquet, HTML, and more.
5. **Strong ecosystem integration** – Works seamlessly with NumPy, Matplotlib, Seaborn, Scikit-learn, and most Python data tools.
6. **Active community & documentation** – Extensive resources, tutorials, and long-term industry adoption.

## Overall Limitations of Pandas

1. **Memory-bound** – Entire dataset must generally fit in RAM; struggles with very large (multi-GB/TB) datasets.
2. **Single-threaded core operations** – Many operations don't natively parallelize across CPU cores (though newer versions/Modin/Dask can help).
3. **Performance overhead on row-wise Python loops** – `.apply()` with custom Python functions can be slow compared to vectorized alternatives.
4. **API complexity/inconsistency** – Multiple ways to do the same thing (`.loc`, `.iloc`, chained indexing) can confuse beginners and cause subtle bugs.
5. **Not ideal for truly big data** – For datasets beyond memory limits, tools like Apache Spark, Dask, or Polars are often better suited.
6. **Version differences** – Behavior and defaults have changed across pandas versions (e.g., copy-on-write changes in pandas 2.x), which can break older code.

## Minimum 5 Interview Questions with Answers

**Q1. What is the difference between a Pandas Series and a DataFrame?**
A Series is a one-dimensional labeled array that can hold a single data type efficiently, similar to one column of data. A DataFrame is a two-dimensional labeled structure (rows and columns) where each column is essentially a Series, and different columns can hold different data types.

**Q2. What is the difference between `.loc[]` and `.iloc[]`?**
`.loc[]` is **label-based** indexing — it selects rows/columns using their index labels or column names (e.g., `df.loc[102, "Name"]`). `.iloc[]` is **position-based** indexing — it selects rows/columns using integer positions, similar to standard Python list indexing (e.g., `df.iloc[0, 1]`). A common pitfall is that after filtering a DataFrame, the index labels are no longer sequential, so `.iloc[0]` and `.loc[0]` may return different rows.

**Q3. How does Pandas handle missing data, and how can you deal with it?**
Missing data is represented as `NaN` (Not a Number) for numeric/object columns, or `NaT` for datetime columns. Pandas provides methods like `isna()`/`isnull()` to detect missing values, `dropna()` to remove rows/columns containing them, and `fillna()` to impute values (e.g., with the mean, median, a constant, or forward/backward fill).

**Q4. What is the difference between `df.copy()` and simply assigning a DataFrame to another variable?**
Assigning `df2 = df1` creates a new variable name pointing to the **same underlying object**, so modifying `df2` can unintentionally modify `df1`. Using `df2 = df1.copy()` creates an independent copy in memory, so changes to `df2` do not affect `df1`. This distinction is a common source of the `SettingWithCopyWarning`.

**Q5. What is the purpose of `groupby()` in Pandas, and can you give an example?**
`groupby()` implements the "split-apply-combine" pattern: it splits data into groups based on some key (e.g., a column value), applies an aggregate function (like `sum`, `mean`, `count`) to each group independently, and combines the results into a new DataFrame/Series. Example: `df.groupby("Department")["Salary"].mean()` returns the average salary per department.

**Q6. What is the difference between `merge()`, `join()`, and `concat()` in Pandas?**
`merge()` combines DataFrames based on common columns/keys (similar to SQL joins: inner, left, right, outer). `join()` is a convenience method primarily for combining DataFrames based on their **index**. `concat()` simply stacks DataFrames together along a given axis (rows or columns) without matching on keys, useful for appending similar datasets.

**Q7. Why might you convert a column to the `category` dtype, and what are the trade-offs?**
Converting a column with a limited number of repeated string values (e.g., "Male"/"Female", or product categories) to `category` dtype reduces memory usage (internally stored as integer codes) and can speed up operations like `groupby()` and sorting. The trade-off is that it's best suited for columns with relatively few unique values; for high-cardinality columns, the benefit shrinks and manipulation can be slightly less intuitive.

## Self Reflection

- **What did I learn?**
  I learned what Pandas is, why it's essential for data analysis, and the core building blocks — Series and DataFrame — including how to create them from multiple sources, understand and convert data types, work with the Index and Columns, and read/write data across common file formats (CSV, JSON, Excel).

- **How does this connect to real-world work?**
  Nearly every data analysis, business intelligence, or machine learning project begins with loading raw data into a Pandas DataFrame, inspecting it, cleaning it, and reshaping it — the exact skills covered in this notebook are the daily toolkit of data analysts and data scientists.