## Notebook 6 – Data Inspection

### Data Inspection

Data inspection is the process of examining a dataset to understand its structure, size, data types, missing values, and basic statistics.

Pandas provides several functions and attributes to quickly inspect a DataFrame.

In [1]:
import pandas as pd
data = {
    "Name": ["Hema", "Ravi", "Priya", "Arun", "Kavi", "John"],
    "Age": [21, 22, 20, 23, 21, 24],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR"],
    "Salary": [45000, 40000, 50000, 55000, 48000, 42000],
    "Experience": [1, 2, 1, 3, 2, 4]
}
df = pd.DataFrame(data)
df

    Name  Age Department  Salary  Experience
0   Hema   21         IT   45000           1
1   Ravi   22         HR   40000           2
2  Priya   20         IT   50000           1
3   Arun   23    Finance   55000           3
4   Kavi   21         IT   48000           2
5   John   24         HR   42000           4

## 1. head()

The `head()` method displays the first few rows of a DataFrame.

By default, it displays the first **5 rows**.

**Real-World Example**
Quickly checking the first records of a customer dataset.

**Business Example**
A business analyst can check the first few sales records to verify whether the data was loaded correctly.

**AI/ML Example**
Before training a model, we can use `head()` to understand the structure and values of the dataset.

In [2]:
df.head()

    Name  Age Department  Salary  Experience
0   Hema   21         IT   45000           1
1   Ravi   22         HR   40000           2
2  Priya   20         IT   50000           1
3   Arun   23    Finance   55000           3
4   Kavi   21         IT   48000           2

**Output Explanation**

The first 5 rows of the DataFrame are displayed.

We can also specify the number of rows:

```python
df.head(3)

## 2. tail()

The `tail()` method displays the last few rows of a DataFrame.

By default, it displays the last **5 rows**.

**Real-World Example**
Checking the latest records in a dataset.

**Business Example**
A company can check the most recently added sales records.

**AI/ML Example**
It can help verify whether the final records of a dataset were loaded correctly.

In [3]:
df.tail()

    Name  Age Department  Salary  Experience
1   Ravi   22         HR   40000           2
2  Priya   20         IT   50000           1
3   Arun   23    Finance   55000           3
4   Kavi   21         IT   48000           2
5   John   24         HR   42000           4

**Output Explanation**

The last 5 rows of the DataFrame are displayed.

Use `df.tail(3)` to display the last 3 rows.

## 3. sample()

The `sample()` method returns random rows from a DataFrame.

**Real-World Example**
Randomly checking records from a large dataset.

**Business Example**
A quality team can randomly inspect customer transactions.

**AI/ML Example**
Randomly inspecting training data can help identify unexpected values or data quality issues.

In [4]:
df.sample(3)

   Name  Age Department  Salary  Experience
4  Kavi   21         IT   48000           2
5  John   24         HR   42000           4
3  Arun   23    Finance   55000           3

**Output Explanation**

Three random rows are selected from the DataFrame.

The rows may be different each time because the selection is random.

## 4. info()

The `info()` method provides a summary of a DataFrame.

It shows:

- Number of rows
- Column names
- Non-null values
- Data types
- Memory usage

**Real-World Example**
Checking the structure and quality of a newly received dataset.

**Business Example**
Before analyzing employee data, an analyst can check whether columns contain missing values.

**AI/ML Example**
`info()` helps identify missing values and incorrect data types before preprocessing.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         6 non-null      int64
 2   Department  6 non-null      str
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), str(2)
memory usage: 414.0 bytes

**Output Explanation**

The output shows the number of entries, column names, non-null counts, data types, and approximate memory usage of the DataFrame.

## 5. describe()

The `describe()` method generates descriptive statistics for numerical columns.

It commonly returns:

- Count
- Mean
- Standard deviation
- Minimum
- 25th percentile
- Median
- 75th percentile
- Maximum

**Real-World Example**
Understanding the distribution of employee salaries.

**Business Example**
A company can analyze average sales, minimum sales, and maximum sales.

**AI/ML Example**
It helps understand feature distributions and identify unusual values before model training.

In [6]:
df.describe()

             Age        Salary  Experience
count   6.000000      6.000000    6.000000
mean   21.833333  46666.666667    2.166667
std     1.471960   5501.514943    1.169045
min    20.000000  40000.000000    1.000000
25%    21.000000  42750.000000    1.250000
50%    21.500000  46500.000000    2.000000
75%    22.750000  49500.000000    2.750000
max    24.000000  55000.000000    4.000000

**Output Explanation**

The output summarizes the numerical columns.

For example, the `Salary` column shows its average, minimum, maximum, and other statistical values.

## 5. describe()

The `shape` attribute returns the dimensions of a DataFrame.

It returns:

```text
(number_of_rows, number_of_columns)

**Real-World Example**
Checking the size of a dataset.

**Business Example**
An analyst can quickly determine how many customer records and features are available.

**AI/ML Example**
Before model training, shape helps verify the number of samples and features.

In [7]:
df.shape

(6, 5)

**Output Explanation**

If the output is `(6, 5)`, it means:

- **6 rows**
- **5 columns**

## 7. columns

The `columns` attribute returns the names of all columns in a DataFrame.

**Real-World Example**
Checking the available fields in a dataset.

**Business Example**
An analyst can identify whether required business fields such as Salary or Department exist.

**AI/ML Example**
It helps identify the features available for model training.

In [8]:
df.columns

Index(['Name', 'Age', 'Department', 'Salary', 'Experience'], dtype='str')

**Output Explanation**

The output displays all column names available in the DataFrame.

## 8. dtypes

The `dtypes` attribute shows the data type of each column.

Common Pandas data types include:

- `int64`
- `float64`
- `object`
- `bool`
- `datetime64`

**Real-World Example**
Checking whether a dataset contains numeric, text, or date columns.

**Business Example**
A salary column should normally be numeric for calculations.

**AI/ML Example**
Machine learning algorithms generally require features to be converted into suitable numerical formats.

In [9]:
df.dtypes

Name            str
Age           int64
Department      str
Salary        int64
Experience    int64
dtype: object

**Output Explanation**

The output displays the data type of every column.

For example, `Age` and `Salary` are integer columns, while `Name` and `Department` contain text data.

## 9. memory_usage()

The `memory_usage()` method shows how much memory each column uses.

**Real-World Example**
Checking memory consumption when working with large datasets.

**Business Example**
A company processing millions of transactions can monitor memory usage to improve performance.

**AI/ML Example**
Reducing unnecessary memory usage can make data preprocessing more efficient.

The `deep=True` option provides a more accurate memory calculation for object-type columns.

In [10]:
df.memory_usage()

Index         132
Name           73
Age            48
Department     65
Salary         48
Experience     48
dtype: int64

In [11]:
df.memory_usage(deep=True)

Index         132
Name           73
Age            48
Department     65
Salary         48
Experience     48
dtype: int64

**Output Explanation**

The output shows the memory used by each column in bytes.

`deep=True` provides a more detailed memory calculation for object/string columns.

## 10. nunique()

The `nunique()` method returns the number of unique values in each column.

**Real-World Example**
Finding how many unique customers, cities, or products exist.

**Business Example**
A company can determine how many unique departments or product categories are present.

**AI/ML Example**
It helps identify categorical features with many or few unique values.

In [13]:
df.nunique()

Name          6
Age           5
Department    3
Salary        6
Experience    4
dtype: int64

**Output Explanation**

The output shows the number of unique values in each column.

For example, the `Department` column has multiple repeated values but only a few unique departments.

## 11. value_counts()

The `value_counts()` method counts how frequently each unique value occurs in a column.

**Real-World Example**
Counting how many customers belong to each city.
    
**Business Example**
A company can determine how many employees work in each department.

**AI/ML Example**
It can be used to understand the distribution of categorical target classes and identify class imbalance.

In [14]:
df["Department"].value_counts()

Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64

**Output Explanation**

The output shows the number of employees in each department.

For example, if `IT` appears 3 times, it means 3 employees belong to the IT department.

# Advantages

- Quickly understand dataset structure.
- Easy to identify data types.
- Helps detect missing values.
- Provides basic statistical information.
- Helps identify categorical distributions.
- Useful for data cleaning and preprocessing.
- Supports efficient exploratory data analysis (EDA).
- Helps prepare datasets for AI/ML workflows.

# Limitations

- Inspection methods do not completely clean the data.
- `describe()` provides only basic statistics.
- `info()` does not explain the meaning of the data.
- Large datasets may still require advanced profiling tools.
- `value_counts()` can produce large outputs for high-cardinality columns.
- Statistical summaries alone may not reveal all data quality problems.

# Interview Questions and Answers

### 1. What is the purpose of `head()`?

**Answer:**  `head()` displays the first few rows of a DataFrame. By default, it displays 5 rows.


### 2. What is the difference between `head()` and `tail()`?

**Answer:**  `head()` displays the first rows, while `tail()` displays the last rows of a DataFrame.


### 3. What does `shape` return?

**Answer:**  
`shape` returns the number of rows and columns in the format `(rows, columns)`.


### 4. What is the purpose of `info()`?

**Answer:**  `info()` provides information about columns, data types, non-null values, number of rows, and memory usage.


### 5. What does `describe()` do?

**Answer:**  `describe()` generates descriptive statistics such as count, mean, standard deviation, minimum, percentiles, and maximum for numerical columns.


### 6. What is the difference between `nunique()` and `value_counts()`?

**Answer:**  `nunique()` returns the number of unique values, while `value_counts()` returns the frequency of each unique value.


### 7. What does `dtypes` show?

**Answer:**  `dtypes` shows the data type of each column in a DataFrame.


### 8. Why is `sample()` useful?

**Answer:**  `sample()` randomly selects rows, which is useful for quickly checking different parts of a dataset.


### 9. What is the purpose of `memory_usage()`?

**Answer:**  It shows the amount of memory used by the DataFrame or its individual columns.

### 10. How can `value_counts()` help in machine learning?

**Answer:**  It can help understand the distribution of categorical values and identify class imbalance in classification problems.

## Self Reflection

-Learned how to inspect datasets using Pandas.

-Understood the use of head(), tail(), and sample().

-Learned to check dataset structure using info() and shape.

-Understood how to analyze data types using dtypes.

-Learned to generate summary statistics using describe().

-Understood how to check unique values using nunique().

-Learned to analyze category frequencies using value_counts().

-Understood the importance of checking memory usage.

-Learned how data inspection helps in data cleaning and AI/ML preprocessing.